### PR TITLE
Adds ability to call corresponding cljstyle task in Ruby Leiningen

### PR DESCRIPTION
**Pull request by JordanRobinson**
Please see corresponding PR in [Rake Leiningen](https://github.com/infrablocks/ruby_leiningen/pull/2)

### CODE REVIEW

**Review by tobyclemson — CHANGES_REQUESTED** [review]
You'll need to bump `ruby_terraform` to 0.21.0 now that the underlying change has been released.

Looks good otherwise.

**Comment by tobyclemson** [comment]
I wonder if we should either:
- Update the `Check` task set to use `Style` instead of `Format`

**Comment by JordanRobinson** [comment]
Version updated, let me know if I missed anything.

On updating the `Check` task, my thoughts were that if we update the `Check` task to point at `Style`, this will be very unexpected for anyone using `Check` currently, since the rules of `fmt` and `style` are different. As such I was going for back-compatibility in not changing it and expecting the user to use something like `RakeLeiningen.define_check_tasks(format_task_name: 'Style')` - but more than happy to take a steer on this, and don't feel particularly strongly on it.

**Comment by tobyclemson** [comment]
Agree on the backwards compatibility, although if time passes and cljstyle takes off, I might do that anyway, with a major version bump. 

If you go with `format_task_name` you would have to separately define the style task in your Rakefile. If instead you went with something like:

```ruby
RakeLeiningen.define_check_tasks(
    format_task_class: RakeLeiningen::Tasks::Style)
```

...then the definition can be handled in the background for you. Makes it a bit easier to roll out.

**Comment by JordanRobinson** [comment]
That makes sense and sounds much better.

I must admit though I'm not sure what changes that would need in the `checks.rb` class - I'm guessing we'd need to pick that up as a parameter, but I'm not sure how the `RakeFactory::DynamicValue` part would work with passing a class through, I don't suppose you know of a good example we can reuse?

**Comment by tobyclemson** [comment]
Hmm yes you are right. Those things happen at different times in the lifecycle and it seems we'd need some enhancements to RakeFactory to make this possible.

I'll add it to the backlog and merge this for now - it gets you what you need, anything else is just syntactic sugar.

**Comment by tobyclemson** [comment]
Will let you know once the release version is out.

**Comment by tobyclemson** [comment]
Version [0.28.0](https://rubygems.org/gems/rake_leiningen/versions/0.28.0) includes this change.

**Pull request merged**
